## **Case Study: Student Performance Analysis with Linear Algebra** ##

**3.1 Representing data as a matrix**

Student_scores_sheet (4x3):  

        rows = students , 
        columns = subjects

S = 
\begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75\\
95 & 88 & 92\\
70 & 60 & 65\\
\end{bmatrix} 
                

In [2]:
# 3.1 Representing data as a matrix 
import numpy as np

student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )

student_scores_sheet

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])


**3.2   Compute the total Score for each student by summing across the row vector**

- Total Scores / student:
```
    student_1 = (80 + 70 + 90) = 240,
    student_2 = (60 + 85 + 75) = 220,
    student_3 = (95 + 88 + 92)  = 275,
    student_4 = (70 + 60 + 65)  = 195
```
Students_record= 

\begin{bmatrix}
Students & Total Scores\\
Student_1 & 240 \\
Student_2 & 220\\
Student_3 & 275\\
Student_4 & 195\\
\end{bmatrix} 

In [3]:
# 3.2 Computing the total scores for each student summing across the row vector using numpy
# Import libraries
import numpy as np

student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )

total_scores_array = np.sum(student_scores_sheet, axis=1)
print(f"The total score for each student: {total_scores_array}")



The total score for each student: [240 220 275 195]



**3.3   Applying Weights (Scalar Multiplication)**

- Maths is twice as important as the other subject i.e. scalar = 2 

Maths_subjects = 
2 x 
\begin{bmatrix}
80 \\ 60\\ 95\\ 70\\
\end{bmatrix} 
```
Maths_score_student1 = (2x80) = 160
Maths_score_student2 = (2x60) = 120
Maths_score_student3 = (2x70) = 190
Maths_score_student4 = (2x80) = 140
```
New_maths_scores = 

\begin{bmatrix}
Students & Scores\\
Student_1 & 160 \\
Student_2 & 120\\
Student_3 & 190\\
Student_4 & 140\\
\end{bmatrix} 

New_scores= 
\begin{bmatrix}
160 & 70 & 90 \\
120 & 85 & 75\\
190 & 88 & 92\\
140 & 60 & 65\\
\end{bmatrix} 

In [4]:
# Applying Weights (Scalar Multiplication)
    # Maths is twice as important as the other subject i.e. scalar = 2

import numpy as np

scalar = 2
student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )
student_maths_scores = np.array(student_scores_sheet[:, 0])

new_maths_scores = (scalar * student_maths_scores)

new_scores_sheet = np.array(
                            [[160,70,90],
                            [120,85,75],
                            [190,88,92],
                            [140,60,65]]
                            )
print(new_scores_sheet)

print(f"The new maths scores for each student is:\n")
print(f"Student_1:\n{new_maths_scores[0]}")
print(f"Student_2:\n{new_maths_scores[1]}")
print(f"Student_3:\n{new_maths_scores[2]}")
print(f"Student_4:\n{new_maths_scores[3]}")
                    

[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
The new maths scores for each student is:

Student_1:
160
Student_2:
120
Student_3:
190
Student_4:
140



**3.4   Average Score per Subject(Matrix Operations)**

- Compute the average score for each subject by calculating the column-wise mean.

Student_scores_sheet (4x3):  

        rows = students , 
        columns = subjects

\begin{bmatrix}
Students & Maths & English & Science \\
Student_1 & 80 & 70 & 90 \\
Student_2 & 60 & 85 & 75\\
Student_3 & 95 & 88 & 92\\
Student_4 & 70 & 60 & 65\\
\end{bmatrix} 

Total_students = 4

Avg_subject = Scores_subject / Total_students

```
Avg_maths_score = (80 + 60 + 95 + 70)/4 = 305/4 = 76.25
Avg_english_score = (70 + 85 + 88 + 60)/4 = 305/4 = 75.75
Avg_science_score = (90 + 75 + 92 + 65)/4 = 322/4 = 80.5
```

Average_score= 

\begin{bmatrix}
Subjects & Average Scores\\
Maths & 76.25 \\
English & 75.75\\
Science & 80.5\\
\end{bmatrix} 




In [5]:
# 3.4   Average Score per Subject(Matrix Operations)
 # Compute the average score for each subject by calculating the column-wise mean.

import numpy as np
student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )
avg_maths_score = np.mean(student_scores_sheet[:, 0])
avg_english_score = np.mean(student_scores_sheet[:, 1])
avg_science_score = np.mean(student_scores_sheet[:, 2])

print(f"The average score for maths is {avg_maths_score}")
print(f"The average score for english is {avg_english_score}")
print(f"The average score for science is {avg_science_score}")

The average score for maths is 76.25
The average score for english is 75.75
The average score for science is 80.5


**3.5   Final Grades using Matrix Multiplication)**

- Compute the average score for each subject by calculating the column-wise mean.

Student_scores_sheet (4x3):  

        rows = students , 
        columns = subjects

\begin{bmatrix}
Students & Maths & English & Science \\
Student_1 & 80 & 70 & 90 \\
Student_2 & 60 & 85 & 75\\
Student_3 & 95 & 88 & 92\\
Student_4 & 70 & 60 & 65\\
\end{bmatrix} 

```
weight_vector = [ 
        30% = 0.3 = maths
        40% = 0.4 = english
        30% = 0.3 = science
        ]

weight_vector (3x1)

Final_grades (4x1)= student_scores x weight_vector
        [
        student_1_grade = [(80 x 0.3), (70 x 0.4), (90 x 0.3)]
        student_2_grade = [(60 x 0.3), (85 x 0.4), (75 x 0.3)]
        student_3_grade = [(95 x 0.3), (88 x 0.4), (92 x 0.3)]
        student_4_grade = [(70 x 0.3), (60 x 0.4), (65 x 0.3)]
        ]               
Final_grades (4x1)= [
        student_1_grade = [24   28        27]
        student_2_grade = [18   34      22.5]
        student_3_grade = [28.5 35.2    27.6]
        student_4_grade = [21   24      19.5]
        ] 

- Final_grade / student:

    student_1 = (24 + 28 + 27) = 79,
    student_2 = (18 + 34 + 22.5) = 74.5,
    student_3 = (28.5 + 35.2 + 27.6)  = 91.3,
    student_4 = (21  + 24 + 19.5)  = 64.5

        A = 75 - 100
        B = 65 - 74
        C = 64 - 55
        D = 54 - 45
        E = 44 - 40
        F = 39 - 0

```
Students_record= 

\begin{bmatrix}
Students & Scores &Grades\\
Student_1 & 79 & A\\
Student_2 & 74.5 & B\\
Student_3 & 91.3 & A\\
Student_4 & 64.5 & C\\
\end{bmatrix} 

In [6]:
# 3.5   Final Grades using Matrix Multiplication)
    # Compute the average score for each subject by calculating the column-wise mean.

weight_vector= [0.3, 0.4, 0.3]


student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )
student_1 = np.array(student_scores_sheet[0, :])
student_2 = np.array(student_scores_sheet[1, :])
student_3 = np.array(student_scores_sheet[2, :])
student_4 = np.array(student_scores_sheet[3, :])

# Calculating the sum of the students scores
final_grade_student_1 = np.sum(student_1 * weight_vector)
final_grade_student_2 = np.sum(student_2 * weight_vector)
final_grade_student_3 = np.sum(student_3 * weight_vector)
final_grade_student_4 = np.sum(student_4 * weight_vector)

# Grade for each scores 
Grades = {
    '75 - 100' : 'A',
    '65 - 74' : 'B',
    '64 - 55':  'C',
    '54 - 45' : 'D',
    '44 - 40' : 'E',
    '39 - 0' : 'F',
    }



print(f"The Final Grades:\n")
print(f"Student_1: {final_grade_student_1}% ({Grades['75 - 100']})")
print(f"Student_2: {final_grade_student_2}% ({Grades['65 - 74']})")
print(f"Student_3: {final_grade_student_3}% ({Grades['75 - 100']})")
print(f"Student_4: {final_grade_student_4}% ({Grades['64 - 55']})")

                    


The Final Grades:

Student_1: 79.0% (A)
Student_2: 74.5% (B)
Student_3: 91.3% (A)
Student_4: 64.5% (C)


**3.6  Comparing Students (Vector Subtraction)**
- Compare two students’ performances by subtracting their score vectors.

   
Student_scores_sheet (4x3):  

        rows = students , 
        columns = subjects

\begin{bmatrix}
Students & Maths & English & Science \\
Student_1 & 80 & 70 & 90 \\
Student_2 & 60 & 85 & 75\\
\end{bmatrix}

```
Students_performance_comparison = (80-60, 70-85, 90-75)
                                = (20, -15, 15)
                    
Maths : Student_1 performed better than Student_2
English: Student_2 performed better than Student_1
Science: Student_1 performed better than Student_2
```

In [7]:
# 3.6 Comparing Students (Vector Subtraction)
# Comparing two students' performance by subtracting their score vectors

student_scores_sheet = np.array(
                                [[80,70,90],
                                [60,85,75],
                                [95,88,92],
                                [70,60,65]]
                                )
student_1 = np.array(student_scores_sheet[0, :])
student_2 = np.array(student_scores_sheet[1, :])

students_performance = np.array( student_1 - student_2)
print(students_performance)
print(f"In Maths, Student 1 performed better than Student 2 by {students_performance[0]} marks")
print(f"In English, Student 2 performed better than Student 1 by {students_performance[1]} marks")
print(f"In Science, Student 1 performed better than Student 2 by {students_performance[2]} marks")


[ 20 -15  15]
In Maths, Student 1 performed better than Student 2 by 20 marks
In English, Student 2 performed better than Student 1 by -15 marks
In Science, Student 1 performed better than Student 2 by 15 marks


# **5.0 ADD-ON-EXERCISE** #

**5.1   Create a new 5 x 4 matrix of scores (5 students, 4 Subjects)**

Student_scores_sheet (5x4):  

        rows = students , 
        columns = subjects

S = 
\begin{bmatrix}
57 & 96 & 57 & 86 \\
88 & 44 & 92 & 82\\
73 & 75 & 65 & 99\\
63 & 86 & 78 & 63\\
74 & 81 & 59 & 87\\
\end{bmatrix} 


- Compute each student's total score and the average per subject

Total_Scores_student:
```
    student_1 = (57 + 96 + 57 + 86) = 296,
    student_2 = (88 + 44 + 92 + 82) = 306,
    student_3 = (73 + 75 + 65 + 99)  = 312,
    student_4 = (63 + 86 + 78 + 63)  = 290,
    student_5 = (74 + 81 + 59 + 87)  = 301
```
Students_record= 

\begin{bmatrix}
Students & Total Scores\\
Student_1 & 296 \\
Student_2 & 306\\
Student_3 & 312\\
Student_4 & 290\\
Student_5 & 301\\
\end{bmatrix} 
                
Total_students = 5

Avg_subject = Scores_subject / Total_students

```
Avg_maths_score = (57 + 88 + 73 + 63 + 74)/5 = 355/5 = 71.0
Avg_english_score = (96 + 44 + 75 + 86 + 81)/5 = 382/5 = 76.4
Avg_biology_score = (57 + 92 + 65 + 78 + 59)/5 = 351/5 = 70.2
Avg_physics_score = (86 + 82 + 99 + 63 + 87)/5 = 417/5 = 83.4
```

Average_score= 

\begin{bmatrix}
Subjects & Average Scores\\
Maths & 71.0 \\
English & 76.4\\
Biology & 70.2\\
Physics & 83.4\\
\end{bmatrix} 




In [8]:
# 5.1   Create a new 5 x 4 matrix of scores (5 students, 4 Subjects)
import random
students_score_sheet = np.random.randint(40, 100, (5, 4)) # rows (1)= students, columns (0) = subjects


# Using these first random scores generated after running
subjects = ['Maths', 'English', 'Biology', 'Physics'] 
students_scores_sheet = np.array(
                                [[57, 96, 57, 86],
                                [88, 44, 92, 82],
                                [73, 75, 65, 99],
                                [63, 86, 78, 63],
                                [74, 81, 59, 87]]
                                )
                
# Compute each student's total score and the average per subject
students_total_scores = np.sum(students_scores_sheet, axis=1)
print(f"The total for each student is {students_total_scores}")

# Calculating the average per subject
avg_maths_score = np.mean(students_scores_sheet[:, 0], axis=0)
avg_english_score = np.mean(students_scores_sheet[:, 1], axis=0)
avg_biology_score = np.mean(students_scores_sheet[:, 2], axis=0)
avg_physics_score = np.mean(students_scores_sheet[:, 3], axis=0)

print(f"The average score for maths is {avg_maths_score}")
print(f"The average score for english is {avg_english_score}")
print(f"The average score for biology is {avg_biology_score}")
print(f"The average score for physics is {avg_physics_score}")



The total for each student is [296 306 312 290 301]
The average score for maths is 71.0
The average score for english is 76.4
The average score for biology is 70.2
The average score for physics is 83.4


**5.2 Suppose one subject (e.g.,Science) is 3times more important than others.**

Biology is thrice as important as the other subject i.e. scalar = 3

Biology_subject = 
3 x 
\begin{bmatrix}
57 \\ 92\\ 65\\ 78\\59\\
\end{bmatrix} 
```
biology_score_student1 = (3x57) = 171
biology_score_student2 = (3x92) = 276
biology_score_student3 = (3x65) = 195
biology_score_student4 = (3x78) = 234
biology_score_student5 = (3x59) = 177
```
New_biology_scores = 

\begin{bmatrix}
Students & Scores\\
Student_1 & 171 \\
Student_2 & 276\\
Student_3 & 195\\
Student_4 & 234\\
Student_5 & 177\\
\end{bmatrix} 

New_scores= 

\begin{bmatrix}
57 & 96 & 171 & 86\\
88 & 44 & 276 & 82\\
73 & 75 & 195 & 99\\
63 & 86 & 234 & 63\\
74 & 81 & 177 & 87\\
\end{bmatrix} 


- Apply scalar multiplication and recompute totals.

Total_Scores_student:
```
    student_1 = (57 + 96 + 171 + 86) = 410,
    student_2 = (88 + 44 + 276 + 82) = 490,
    student_3 = (73 + 75 + 195 + 99)  = 442,
    student_4 = (63 + 86 + 234 + 63)  = 446,
    student_5 = (74 + 81 + 177 + 87)  = 419
```
New_total_score  =

\begin{bmatrix}
Students & Total Scores\\
Student_1 & 410 \\
Student_2 & 490\\
Student_3 & 442\\
Student_4 & 446\\
Student_5 & 419\\
\end{bmatrix} 


In [9]:
#5.2 Applying Weights (Scalar Multiplication)
    # Biology is thrice as important as the other subject i.e. scalar = 3

import numpy as np

scalar = 3
subjects = ['Maths', 'English', 'Biology', 'Physics'] 
students_scores_sheet = np.array(
                                [[57, 96, 57, 86],
                                [88, 44, 92, 82],
                                [73, 75, 65, 99],
                                [63, 86, 78, 63],
                                [74, 81, 59, 87]]
                                )
                
# Compute each student's total score and the average per subject
student_biology_scores = np.array(students_scores_sheet[:, 2])

new_biology_scores = (scalar * student_biology_scores)

new_scores_sheet = np.array(
                                [[57, 96, new_biology_scores[0], 86],
                                [88, 44, new_biology_scores[1], 82],
                                [73, 75, new_biology_scores[2], 99],
                                [63, 86, new_biology_scores[3], 63],
                                [74, 81, new_biology_scores[4], 87]]
                                )
print(new_scores_sheet)

print(f"The new maths scores for each student is:\n")
print(f"Student_1:\n{new_biology_scores[0]}")
print(f"Student_2:\n{new_biology_scores[1]}")
print(f"Student_3:\n{new_biology_scores[2]}")
print(f"Student_4:\n{new_biology_scores[3]}")
print(f"Student_5:\n{new_biology_scores[4]}")

# Recomputing the totals using the new biology scores
new_students_total_scores = np.sum(new_scores_sheet, axis=1)
print(f"The total for each student is {new_students_total_scores}")


[[ 57  96 171  86]
 [ 88  44 276  82]
 [ 73  75 195  99]
 [ 63  86 234  63]
 [ 74  81 177  87]]
The new maths scores for each student is:

Student_1:
171
Student_2:
276
Student_3:
195
Student_4:
234
Student_5:
177
The total for each student is [410 490 442 446 419]


**5.3 Define new weights for grading (e.g.,40%,20%,30%,10%)**

Student_scores_sheet (5x4):  

        rows = students , 
        columns = subjects

S = 
\begin{bmatrix}
57 & 96 & 57 & 86 \\
88 & 44 & 92 & 82\\
73 & 75 & 65 & 99\\
63 & 86 & 78 & 63\\
74 & 81 & 59 & 87\\
\end{bmatrix} 


```
weight_vector = [ 
        30% = 0.3 = maths
        40% = 0.4 = english
        20% = 0.2 = biology
        10% = 0.1 = physics
        
        ]

weight_vector (4x1)

Final_grades (5x1)= student_scores x weight_vector
        [
        student_1_grade = [(57 x 0.3), (96 x 0.4), (57 x 0.2), (86 x 0.1) ]
        student_2_grade = [(88 x 0.3), (44 x 0.4), (92 x 0.2), (82 x 0.1)]
        student_3_grade = [(73 x 0.3), (75 x 0.4), (65 x 0.2), (99 x 0.1)]
        student_4_grade = [(63 x 0.3), (86 x 0.4), (78 x 0.2), (63 x 0.1)]
        student_5_grade = [(74 x 0.3), (81 x 0.4), (59 x 0.2), (87 x 0.1)]
        ]               
Final_grades (5x1)= [
        student_1_grade = [17.1 38.4 11.4  8.6]
        student_2_grade = [26.4 17.6 18.4  8.2]
        student_3_grade = [21.9 30.  13.   9.9]
        student_4_grade = [18.9 34.4 15.6  6.3]
        student_5_grade = [22.2 32.4 11.8  8.7]
        ] 


- Final_grade / student:

    student_1 = (17.1 + 38.4 + 11.4  + 8.6) = 75.5,
    student_2 = (26.4 + 17.6 + 18.4  + 8.2) = 70.6,
    student_3 = (21.9 + 30.  + 13.   + 9.9)  = 74.8,
    student_4 = (18.9 + 34.4 + 15.6  + 6.3)  = 75.2
    student_5 = (22.2 + 32.4 + 11.8  + 8.7)  = 75.1

        A = 75 - 100
        B = 65 - 74
        C = 64 - 55
        D = 54 - 45
        E = 44 - 40
        F = 39 - 0

```
Students_record= 

\begin{bmatrix}
Students & Scores &Grades\\
Student_1 & 75.5 & A\\
Student_2 & 70.6 & B\\
Student_3 & 74.8 & B\\
Student_4 & 75.2 & A\\
Student_5 & 75.1 & A\\
\end{bmatrix} 


- Compute final grades using matrix multiplication

In [10]:
#5.3 Define new weights for grading (e.g.,40%,20%,30%,10%)

subjects = ['Maths', 'English', 'Biology', 'Physics'] 
weight_vector= [0.3, 0.4, 0.2, 0.1]
weight_vector_maths = (30 / 100)
weight_vector_english = (40 / 100)
weight_vector_biology = (20 / 100)
weight_vector_physics = (10 / 100)



# Student array 
students_scores_sheet = np.array(
                                [[57, 96, 57, 86],
                                [88, 44, 92, 82],
                                [73, 75, 65, 99],
                                [63, 86, 78, 63],
                                [74, 81, 59, 87]]
                                )
student_1 = np.array(students_scores_sheet[0, :])
student_2 = np.array(students_scores_sheet[1, :])
student_3 = np.array(students_scores_sheet[2, :])
student_4 = np.array(students_scores_sheet[3, :])
student_5 = np.array(students_scores_sheet[4, :])

# Compute final grades using matrix multiplication
student_1_scores = np.array(student_1 * weight_vector)
student_2_scores = np.array(student_2 * weight_vector)
student_3_scores = np.array(student_3 * weight_vector)
student_4_scores = np.array(student_4 * weight_vector)
student_5_scores = np.array(student_5 * weight_vector)

print("Student Array:\n")
print(student_1_scores)
print(student_2_scores)
print(student_3_scores)
print(student_4_scores)
print(student_5_scores)

# Computing the total score per studenet

final_grade_student_1 = np.sum(student_1 * weight_vector)
final_grade_student_2 = np.sum(student_2 * weight_vector)
final_grade_student_3 = np.sum(student_3 * weight_vector)
final_grade_student_4 = np.sum(student_4 * weight_vector)
final_grade_student_5 = np.sum(student_5 * weight_vector)

# Grades for each scores 
Grades = {
    '75 - 100' : 'A',
    '65 - 74' : 'B',
    '64 - 55':  'C',
    '54 - 45' : 'D',
    '44 - 40' : 'E',
    '39 - 0' : 'F',
    }

# Displaying the final grades
print(f"\nThe Final Grades:\n")
print(f"Student_1: {final_grade_student_1}% ({Grades['75 - 100']})")
print(f"Student_2: {final_grade_student_2}% ({Grades['65 - 74']})")
print(f"Student_3: {final_grade_student_3}% ({Grades['65 - 74']})")
print(f"Student_4: {final_grade_student_4}% ({Grades['75 - 100']})")
print(f"Student_5: {final_grade_student_5}% ({Grades['75 - 100']})")

Student Array:

[17.1 38.4 11.4  8.6]
[26.4 17.6 18.4  8.2]
[21.9 30.  13.   9.9]
[18.9 34.4 15.6  6.3]
[22.2 32.4 11.8  8.7]

The Final Grades:

Student_1: 75.5% (A)
Student_2: 70.60000000000001% (B)
Student_3: 74.80000000000001% (B)
Student_4: 75.2% (A)
Student_5: 75.1% (A)


**5.4  Comparing Students 3 and 4 using (Vector Subtraction)**
- Who perfomed better in each subject?.

   
Student_scores_sheet (2x4):  

        rows = students , 
        columns = subjects

\begin{bmatrix}
Students & Maths & English & Biology & Physics \\
Student3 & 73 & 75 & 65 & 99\\
Student4 & 63 & 86 & 78 & 63\\
\end{bmatrix}

```
Students_performance_by_subjec = ([[73-63], [75-86], [65-78], [99-63]])
                                = [10, -11, -13, 36]
                    
Maths : Student_3 performed better than Student_4
English: Student_4 performed better than Student_3
Biology: Student_4 performed better than Student_3
Physics : Student_3 performed better than Student_4
```

In [12]:
# 5.4  Comparing Students 3 and 4 using (Vector Subtraction)
# Who perfomed better in each subject?.

# Student array 
students_scores_sheet = np.array(
                                [[57, 96, 57, 86],
                                [88, 44, 92, 82],
                                [73, 75, 65, 99],
                                [63, 86, 78, 63],
                                [74, 81, 59, 87]]
                                )

student_3 = np.array(students_scores_sheet[2, :])
student_4 = np.array(students_scores_sheet[3, :])

students_performance = np.array( student_3 - student_4)
print(students_performance)
print(f"In Maths, Student 3 performed better than Student 4 by {students_performance[0]} marks")
print(f"In English, Student 4 performed better than Student 3 by {students_performance[1]} marks")
print(f"In Biology, Student 4 performed better than Student 3 by {students_performance[2]} marks")
print(f"In Physics, Student 3 performed better than Student 4 by {students_performance[3]} marks")


[ 10 -11 -13  36]
In Maths, Student 3 performed better than Student 4 by 10 marks
In English, Student 4 performed better than Student 3 by -11 marks
In Biology, Student 4 performed better than Student 3 by -13 marks
In Physics, Student 3 performed better than Student 4 by 36 marks
