## **Class Task 2** ##

**Given the following matrices:**

``` 
A = 2  -1   3
    0   4   1
```
``` 
B =  1   2  
    -2   0
     5  -3
```


**A. Identify the number of rows and columns in each matrix.**

A = (2 rows, 3 columns) # 2 x 3 matrix

B = (3 rows, 2 columns) # 3 x 2 matrix

**B. Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.**

i.  The matrices can be multiplied:

    A (2, 3), B (3, 2) # The number of columns in A is equal to the number of rows in B. 

    AB = AB(2 x 2) matrix

    B (3, 2), A (2, 3) # The number of columns in B is equal to the number of rows in A. 

    BA = BA(3 x 3) matrix



ii.     AB is a (2 x 2) matrix
``` 
        AB =  [(2x1)+(-1x-2)+(3x5)      (2x2)+(-1x0)+(3x-3)]    =     [19  -5]
              [(0x1)+(4x-2)+(1x5)        (0x2)+(4x0)+(1x-3)]     =    [-3  -3]
```
iii.    BA is a (3 x 3) matrix
``` 
        BA =        [(1x2)+(2x0)    (1x-1)+(2x4)    (1x3)+(2x1)]    =   [2   7   5] 
                    [(-2x2)+(0x0)   (-2x-1)+(0x4)   (-2x3)+(0x1)]   =   [-4  2  -6]
                    [(5x2)+(3x0)    (5x-1)+(-3x4)   (5x3)+(-3x1)]   =   [10 -17  12]
```

```AB != BA```




**C. If the multiplication is defined, compute the resulting matrix. using numpy computation**

In [1]:
# Computing using numpy

import numpy as np

a = np.array([[2, -1, 3], [0, 4, 1]])
b = np.array([[1, 2], [-2, 0], [5, -3]])

# multiplying matrices using dot product
ab = np.dot(a, b)
ba = np.dot(b, a)
print(f"The result for AB (2x2):\n{ab}")
print(f"The result for BA (3x3):\n{ba}")

The result for AB (2x2):
[[19 -5]
 [-3 -3]]
The result for BA (3x3):
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
