**Linear Algebra**

**Given the following matrices:**

``` 
Let:    A = 2  -1           B =  1   4  
            0   3               -2   5

            scalars - (c = 2, d = 3)
```

**Question A**

Compute the following:

- c(A)
- d(B)
- (c+d)A

In [2]:
# Import libraries
import numpy as np

# Scalar Multiplication
c = 2
d = 3

A = np.array([[2 , -1], [0 , 3]])
B = np.array([[1 , 4], [-2 , 5]])

scalar_multiplication_cA = c * A
scalar_multiplication_dB = d * B
print(f"Result cA:\n  {scalar_multiplication_cA}\n")
print(f"Result dB:\n {scalar_multiplication_dB}\n")

# Scalar Addition
scalar_addition = (c+d) * A
print("Result (c+d)A:\n", scalar_addition)

Result cA:
  [[ 4 -2]
 [ 0  6]]

Result dB:
 [[ 3 12]
 [-6 15]]

Result (c+d)A:
 [[10 -5]
 [ 0 15]]


**Question B**

Using the results gotten, verify the scalar Multiplication Properties:

```
Let:    A = 2  -1           B =  1   4  
            0   3               -2   5

            scalars - (c = 2, d = 3)
```

In [3]:
# Properties of Scalar Mulitiplication

# Associativity

associativity1 = (c * d) * A
associativity2 = c * (d * A)

print(f"The result (c.d)A:\n{associativity1}\n")
print(f"The result c(dA):\n{associativity2}\n")
print(f"Associatiativity of scalar multiplication is {np.array_equal(associativity1,associativity2)}")


The result (c.d)A:
[[12 -6]
 [ 0 18]]

The result c(dA):
[[12 -6]
 [ 0 18]]

Associatiativity of scalar multiplication is True


In [4]:
# Distributivity over scalar multiplication

scm_distributivity1 = c * ( A + B)
scm_distributivity2 = (c * A) + (c * B)

print(f"The result c( A + B):\n{scm_distributivity1}\n")
print(f"The result (c * A) + (c * B):\n{scm_distributivity2}\n")
print(f"Distributivity over scalar multiplication is {np.array_equal(scm_distributivity1,scm_distributivity2)}")


The result c( A + B):
[[ 6  6]
 [-4 16]]

The result (c * A) + (c * B):
[[ 6  6]
 [-4 16]]

Distributivity over scalar multiplication is True


In [5]:
# Distributivity over scalar addition

sca_distributivity1 = (c + d) * A
sca_distributivity2 = (c * A) + (d * A)

print(f"The result (c + d) * A:\n{sca_distributivity1}\n")
print(f"The result (c * A) + (d * A):\n{sca_distributivity2}\n")
print(f"Distributivity over scalar Addition is {np.array_equal(sca_distributivity1,sca_distributivity2)}")


The result (c + d) * A:
[[10 -5]
 [ 0 15]]

The result (c * A) + (d * A):
[[10 -5]
 [ 0 15]]

Distributivity over scalar Addition is True


**Question C**

Find the transpose of both matrices:
```
Let:    A = 2  -1           B =  1   4  
            0   3               -2   5
```

In [6]:
# Finding the transpose of both matrices
A = np.array([[2 , -1], [0 , 3]])
B = np.array([[1 , 4], [-2 , 5]])

print(f" The transpose of matrix A is:\n{A.transpose()}")
print(f" The transpose of matrix A is:\n{B.transpose()}")

 The transpose of matrix A is:
[[ 2  0]
 [-1  3]]
 The transpose of matrix A is:
[[ 1 -2]
 [ 4  5]]


**Question D**

Check if (A) and (B) are invertible by computing their determinant. 

-> if they are invertible: find A^-1 and B^-1:
        
```
        Let:    A = 2  -1           B =  1   4  
                    0   3               -2   5
```

In [7]:
# Finding the determinant of A and B
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print(f"The determinant of A is equal to {det_A}, conditon (A^-1 != 0): {det_A != 0}")
print(f"The determinant of B is equal to {det_B}, conditon (B^-1 != 0): {det_B != 0}")

The determinant of A is equal to 6.0, conditon (A^-1 != 0): True
The determinant of B is equal to 13.0, conditon (B^-1 != 0): True


In [8]:
# Finding the inverse of A and B
inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)

print(f"The inverse of A is equal to\n{inv_A}")
print(f"The inverse of A is equal to\n{inv_B}")

The inverse of A is equal to
[[0.5        0.16666667]
 [0.         0.33333333]]
The inverse of A is equal to
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
