### **Task 13 Submission**

**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50.
- Display the array.

In [2]:
# 6 by 6 array array with random int between (1,50)

import numpy as np


array = np.random.randint(1,51, [6,6])
print("The 6 x 6 array:\n", array)

# Alternative using default range
rng = np.random.default_rng()
array_6 = rng.integers(1,51, size=(6,6))
print("The 6x6 using default range:\n", array_6)

The 6 x 6 array:
 [[32 37  9 11 46 35]
 [14 39 27 45  6 11]
 [27 48 15  5 23 21]
 [41 44 36 12 11 11]
 [35 43 48 33 14 15]
 [10 42 14 26 35 48]]
The 6x6 using default range:
 [[21 20  2  7  1 38]
 [27 41 20 33 17 16]
 [13 33 34 19 47 18]
 [40  4 30 26 31 15]
 [14 10 30 27  5  3]
 [19 16  1 27  8 30]]


**Question 2**

Extract the following from the array you created in 
- The first two rows.
- The last three columns. 
- All even numbers in the array.

In [3]:
# Extarcting the first two rows

arrays = np.array(array_6)
print("First two rows are:\n", arrays[0:2])

# Extracting the last three columns
arrays = np.array(array_6)
print("Last three columns are:\n", arrays[:, 3:])

# Extracting the even numbers from the array
arrays = np.array(array_6)
even_nums = arrays[arrays%2==0]
print("The even numbers are:\n", even_nums)

First two rows are:
 [[21 20  2  7  1 38]
 [27 41 20 33 17 16]]
Last three columns are:
 [[ 7  1 38]
 [33 17 16]
 [19 47 18]
 [26 31 15]
 [27  5  3]
 [27  8 30]]
The even numbers are:
 [20  2 38 20 16 34 18 40  4 30 26 14 10 30 16  8 30]


**Question 3**

Perform the following array transformations: 
- Reshape the array into a 3D (3, 2, 6) array. 
- Flatten the reshaped array back to 1D.

In [ ]:
# Reshaping the array above into 3D
reshaped_3D = arrays.reshape(3, 2, 6)
print("Reshaped array (3by2by6):\n", reshaped_3D)

# Flattening the reshaped array to 1D

flattened = arrays.flatten()
print("Flatten array (1D):\n", flattened)


Reshaped array (3by2by6): [[[21 20  2  7  1 38]
  [27 41 20 33 17 16]]

 [[13 33 34 19 47 18]
  [40  4 30 26 31 15]]

 [[14 10 30 27  5  3]
  [19 16  1 27  8 30]]]
Flatten array (1D): [21 20  2  7  1 38 27 41 20 33 17 16 13 33 34 19 47 18 40  4 30 26 31 15
 14 10 30 27  5  3 19 16  1 27  8 30]


**Question 4**

- Generate a 4x4 identity matrix and 
- Replace the diagonal with numbers from 10 to 40, with a step of 10.

In [5]:
# Generate a 4x4 identity matrix
identity = np.eye(4)
print("Identity matrix:\n", identity)

diagonal_no = np.arange(10, 40, 10)
np.fill_diagonal(identity, diagonal_no)
print("The replaced numbers are:\n", diagonal_no)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The replaced numbers are:
 [10 20 30]


**Question 5**

Perform matrix multiplication between: 
- A 3x4 matrix of random integers (1-10) and A 4x3 matrix of random integers (1-10)


In [ ]:
# Generate 3x4 random integers

matrix1 = np.random.randint(1,11, [3, 4])
matrix2 = np.random.randint(1,11, [4, 3])

# # Display the matrix
# matrix_1 = np.array([matrix1])
# matrix_2 = np.array([matrix2])

# Reshape matrix_2 to 3 rows 4 columns
reshape = matrix2.reshape(3,4)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Reshaped Matrix:\n", reshape)
print("Multiplication:\n", matrix1 * reshape)


Matrix 1:
 [[ 8 10 10  8]
 [ 4  6  7  1]
 [ 8  6 10  5]]
Matrix 2:
 [[2 9 3]
 [5 3 1]
 [4 8 9]
 [5 3 7]]
Reshaped Matrix:
 [[2 9 3 5]
 [3 1 4 8]
 [9 5 3 7]]
Multiplication: [[16 90 30 40]
 [12  6 28  8]
 [72 30 30 35]]


**Question 6**

Create a function that takes a 2D NumPy array as input and returns a new array where: 

- All even numbers are squared. 
- All odd numbers are replaced by -1.

In [ ]:
# Generate a function

def array_input():
    # Display output message
    print("---Operations on 2D NumPy---")

    # collect input
    arr_rows = np.array(int(input("Please enter the number of rows: ")))
    arr_cols = np.array(int(input("Please enter the number ofcolums: ")))

    # range the numbers and reshape the columns and rows
    array = np.arange(arr_rows*arr_cols).reshape(arr_rows, arr_cols)

    new_array = np.where(array % 2 == 0, array**2, -1)
    return new_array

print("Array input",array_input())

---Operations on 2D NumPy---
[[  0  -1   4  -1  16]
 [ -1  36  -1  64  -1]
 [100  -1 144  -1 196]
 [ -1 256  -1 324  -1]]
