### **Task 13 Submission**

**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50.
- Display the array.

In [10]:
# 6 by 6 array array with random int between (1,50)

import numpy as np


array = np.random.randint(1,51, [6,6])
print("The 6 x 6 array:\n", array)

# Alternative using default range
rng = np.random.default_rng()
array_6 = rng.integers(1,51, size=(6,6))
print("The 6x6 using default range:\n", array_6)

The 6 x 6 array:
 [[13 31 24 32 32 27]
 [ 4 48 49 46 24  8]
 [23 12 42 49 43 16]
 [31 37 39 36 43  1]
 [19 48 46 28  6 37]
 [37 33 22  9 42 27]]
The 6x6 using default range:
 [[ 3 21 39 33 15 31]
 [13 14 14  4 25  3]
 [49  4 17 14  7 19]
 [29 27 50 32 39  1]
 [ 2 48 19 37 41 14]
 [ 2 42 19 35 26 17]]


**Question 2**

Extract the following from the array you created in 
- The first two rows.
- The last three columns. 
- All even numbers in the array.

In [11]:
# Extarcting the first two rows

arrays = np.array(array_6)
print("First two rows are:\n", arrays[0:2])

# Extracting the last three columns
arrays = np.array(array_6)
print("Last three columns are:\n", arrays[:, 3:])

# Extracting the even numbers from the array
arrays = np.array(array_6)
even_nums = arrays[arrays%2==0]
print("The even numbers are:\n", even_nums)

First two rows are:
 [[ 3 21 39 33 15 31]
 [13 14 14  4 25  3]]
Last three columns are:
 [[33 15 31]
 [ 4 25  3]
 [14  7 19]
 [32 39  1]
 [37 41 14]
 [35 26 17]]
The even numbers are:
 [14 14  4  4 14 50 32  2 48 14  2 42 26]


**Question 3**

Perform the following array transformations: 
- Reshape the array into a 3D (3, 2, 6) array. 
- Flatten the reshaped array back to 1D.

In [12]:
# Reshaping the array above into 3D
reshaped_3D = arrays.reshape(3, 2, 6)
print("Reshaped array (3by2by6):\n", reshaped_3D)

# Flattening the reshaped array to 1D

flattened = arrays.flatten()
print("Flatten array (1D):\n", flattened)


Reshaped array (3by2by6):
 [[[ 3 21 39 33 15 31]
  [13 14 14  4 25  3]]

 [[49  4 17 14  7 19]
  [29 27 50 32 39  1]]

 [[ 2 48 19 37 41 14]
  [ 2 42 19 35 26 17]]]
Flatten array (1D):
 [ 3 21 39 33 15 31 13 14 14  4 25  3 49  4 17 14  7 19 29 27 50 32 39  1
  2 48 19 37 41 14  2 42 19 35 26 17]


**Question 4**

- Generate a 4x4 identity matrix and 
- Replace the diagonal with numbers from 10 to 40, with a step of 10.

In [13]:
# Generate a 4x4 identity matrix
identity = np.eye(4)
print("Identity matrix:\n", identity)

diagonal_no = np.arange(10, 40, 10)
diag = np.fill_diagonal(identity, diagonal_no)
print("The replaced numbers are:\n", diagonal_no)
print("The replaced numbers are:\n", diag)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The replaced numbers are:
 [10 20 30]
The replaced numbers are:
 None


**Question 5**

Perform matrix multiplication between: 
- A 3x4 matrix of random integers (1-10) and A 4x3 matrix of random integers (1-10)


In [22]:
# Generate 3x4 random integers

matrix1 = np.random.randint(1,11, [3, 4])
matrix2 = np.random.randint(1,11, [4, 3])

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)


# Number of columns in matrix 1 is equal to the number of rows in matrix 2
print("Matrix1 x Matrix2 (3x3):\n", np.dot(matrix1, matrix2))


Matrix 1:
 [[ 3  4  6  8]
 [10  6  4  6]
 [ 4  6  4  2]]
Matrix 2:
 [[7 7 1]
 [2 2 2]
 [1 6 9]
 [5 5 2]]
Matrix1 x Matrix2 (3x3):
 [[ 75 105  81]
 [116 136  70]
 [ 54  74  56]]


**Question 6**

Create a function that takes a 2D NumPy array as input and returns a new array where: 

- All even numbers are squared. 
- All odd numbers are replaced by -1.

In [25]:
# Generate a function

def array_input():
    # Display output message
    print("---Operations on 2D NumPy---")

    # collect input
    arr_rows = np.array(int(input("Please enter the number of rows: ")))
    arr_cols = np.array(int(input("Please enter the number ofcolums: ")))

    # range the numbers and reshape the columns and rows
    array = np.arange(arr_rows*arr_cols).reshape(arr_rows, arr_cols)

    new_array = np.where(array % 2 == 0, array**2, -1)
    return new_array

print("Array input\n",array_input())


---Operations on 2D NumPy---
Array input
 [[ 0 -1]
 [ 4 -1]]
